# Generated by Django 3.2.7 on 2021-09-30 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'comentario', 'verbose_name_plural': 'comentarios'},
        ),
    ]
