# Generated by Django 3.2.7 on 2021-10-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='path',
            field=models.CharField(default='/', max_length=200),
            preserve_default=False,
        ),
    ]
